# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore "src/MailManagement/my-portfolio-be.MailManagement.Api/my-portfolio-be.MailManagement.Api.csproj"
RUN dotnet publish "src/MailManagement/my-portfolio-be.MailManagement.Api/my-portfolio-be.MailManagement.Api.csproj" -c Release -o /app/published

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "my-portfolio-be.MailManagement.Api.dll"]